/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AgreePrivacy: typeof import('./../src/components/agree-privacy/index.vue')['default']
    FreeSchoolSelection: typeof import('./../src/components/free-school-selection/free-school-selection.vue')['default']
    MaskLayer: typeof import('./../src/components/mask-layer/mask-layer.vue')['default']
    MultiplePicker: typeof import('./../src/components/multiple-picker/multiple-picker.vue')['default']
    PageNav: typeof import('./../src/components/page-nav/page-nav.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
