/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AfterSelect: typeof import('./../src/components/lx-cascade-select/after-select.vue')['default']
    AgreePrivacy: typeof import('./../src/components/agree-privacy/index.vue')['default']
    LxCascadeSelect: typeof import('./../src/components/lx-cascade-select/lx-cascade-select.vue')['default']
    PageNav: typeof import('./../src/components/page-nav/page-nav.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
